# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_taskstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
